# Generated by Django 3.2.12 on 2022-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('BC', 'Birthday '), ('AN', 'Anniversary'), ('WC', 'Wedding'), ('CC', 'Congratulations')], max_length=4),
        ),
    ]
