# Generated by Django 3.2.12 on 2022-04-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220405_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='product_buy',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='quantity_prod',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='user_Buying',
            new_name='user',
        ),
    ]
